//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrazyZoo.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrazyZoo.resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisa loom.
        /// </summary>
        public static string AddAnimal {
            get {
                return ResourceManager.GetString("AddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uue looma lisamine:.
        /// </summary>
        public static string AddNewAnimal {
            get {
                return ResourceManager.GetString("AddNewAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanus:.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lisatud..
        /// </summary>
        public static string AnimalAdded {
            get {
                return ResourceManager.GetString("AnimalAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} liitus sama voljeeriga — teised reageerivad!.
        /// </summary>
        public static string AnimalJoined {
            get {
                return ResourceManager.GetString("AnimalJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} eemaldatud..
        /// </summary>
        public static string AnimalRemoved {
            get {
                return ResourceManager.GetString("AnimalRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loomad.
        /// </summary>
        public static string AnimalsHeader {
            get {
                return ResourceManager.GetString("AnimalsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loomade maailm.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sõi {1}..
        /// </summary>
        public static string AteFood {
            get {
                return ResourceManager.GetString("AteFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keskmine vanus kokku: {0:0.0}.
        /// </summary>
        public static string AvgAgeTotal {
            get {
                return ResourceManager.GetString("AvgAgeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hullu tegu.
        /// </summary>
        public static string CrazyButton {
            get {
                return ResourceManager.GetString("CrazyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laaditud {0} looma andmebaasist..
        /// </summary>
        public static string DatabaseLoaded {
            get {
                return ResourceManager.GetString("DatabaseLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andmebaas oli tühi — lisatud algsed loomad..
        /// </summary>
        public static string DatabaseSeeded {
            get {
                return ResourceManager.GetString("DatabaseSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toit.
        /// </summary>
        public static string DefaultFood {
            get {
                return ResourceManager.GetString("DefaultFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimetu.
        /// </summary>
        public static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailid.
        /// </summary>
        public static string DetailsHeader {
            get {
                return ResourceManager.GetString("DetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kukuta toit kõigile.
        /// </summary>
        public static string DropFoodButton {
            get {
                return ResourceManager.GetString("DropFoodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peavoljeer.
        /// </summary>
        public static string EnclosureName {
            get {
                return ResourceManager.GetString("EnclosureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toida.
        /// </summary>
        public static string FeedButton {
            get {
                return ResourceManager.GetString("FeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toit:.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toit kukkus voljeeri 🍎.
        /// </summary>
        public static string FoodDropped {
            get {
                return ResourceManager.GetString("FoodDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loodud ja salvestatud algsed loomad..
        /// </summary>
        public static string InitialAnimalsCreated {
            get {
                return ResourceManager.GetString("InitialAnimalsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanus peab olema ≥ 0.
        /// </summary>
        public static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logi.
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimi:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖÖ sündmus! 🌙.
        /// </summary>
        public static string NightEvent {
            get {
                return ResourceManager.GetString("NightEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loomi pole..
        /// </summary>
        public static string NoAnimals {
            get {
                return ResourceManager.GetString("NoAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See loom ei tee hullu trikki 😅.
        /// </summary>
        public static string NoCrazyAction {
            get {
                return ResourceManager.GetString("NoCrazyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanim: {0} ({1}) — {2} a..
        /// </summary>
        public static string OldestAnimal {
            get {
                return ResourceManager.GetString("OldestAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eemalda loom.
        /// </summary>
        public static string RemoveAnimal {
            get {
                return ResourceManager.GetString("RemoveAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tee hääl.
        /// </summary>
        public static string SoundButton {
            get {
                return ResourceManager.GetString("SoundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liik:.
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika (LINQ).
        /// </summary>
        public static string StatsHeader {
            get {
                return ResourceManager.GetString("StatsHeader", resourceCulture);
            }
        }
    }
}
